"""empty message

Revision ID: 5a021eea09f5
Revises: 
Create Date: 2018-07-05 16:01:34.524335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a021eea09f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.Column('signtime', sa.DateTime(), nullable=False),
    sa.Column('describe', sa.String(length=32), nullable=True),
    sa.Column('picurl', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('news',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('author', sa.String(length=16), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('picurl', sa.String(length=255), nullable=True),
    sa.Column('waitforcheck', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('comments',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('newsid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['newsid'], ['news.pid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['news.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('news')
    op.drop_table('user')
    # ### end Alembic commands ###
